version: '3.8'

services:
  rssbrew:
    build: .
    # Setup DEPLOYMENT_URL (optional if deploy locally), OPENAI_API_KEY(optional), SECRET_KEY in .env
    env_file:
      - .env
    environment:
      - DEBUG=1
      - CRON=*/5 * * * * # cron job for updating feeds
      - TIME_ZONE=Europe/London # Refer to https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      # Redis configuration (optional, defaults shown)
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      # Or use REDIS_URL for full connection string
      # - REDIS_URL=redis://username:password@redis:6379/0
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always