version: '3.8'

services:
  rssbrew:
    build: .
    # Setup DEPLOYMENT_URL (optional if deploy locally), OPENAI_API_KEY(optional), SECRET_KEY in .env
    env_file:
      - .env
    environment:
      - DEBUG=1
      - CRON=*/5 * * * * # cron job for updating feeds
      - TIME_ZONE=Europe/London # Refer to https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    restart: always
